### ISSUE TITLE
APK package got dropped, broke build

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/lsif-upload-action#11]
The git package got bumped in the APK registry, breaking the lsif-upload-action build step. Fixed in #10

3 solutions:

- Keep manually bumping each time this occurs
- Drop the `=2.22.2-rc0` pinned version from the Dockerfile
- Publish Docker images

It looks like `with` fields become capitalized and are passed as environment variables to the Docker container https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepswith

Docker images can be specified in GitHub Actions using `docker://{image}:{tag}`.

Also need to do symmetric work on lsif-{go,typescript,etc.}

**Comment by keegancsmith** [comment]
I think (3) is something we need to do no matter what. A bit silly to be building src-cli everytime / etc. I would still encourage doing (2) as well since I can't think of a situation where we would want to stay on an older version of git. I trust package managers to be doing the right thing.

**Comment by efritz** [comment]
This is going to be handled by https://github.com/sourcegraph/lsif-upload-action/issues/11.
